add a docker snyk scan check result

diff --git a/.github/workflows/main-branch.yaml b/.github/workflows/main-branch.yaml
--- a/.github/workflows/main-branch.yaml
+++ b/.github/workflows/main-branch.yaml
@@ -63,7 +63,7 @@ jobs:
         with:
           mask-password: 'false'
 
-      - name: Build, tag, and push docker image to Amazon ECR
+      - name: Build & tag, and push docker image to Amazon ECR
         env:
           REGISTRY: ${{ steps.login-ecr.outputs.registry }}
           REPOSITORY: digiboard
@@ -82,19 +82,32 @@ jobs:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         with:
           image: ${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY_NAME }}:${{ env.IMAGE_TAG }}
-          args: --file=Dockerfile --severity-threshold=high
+          args: --file=Dockerfile --severity-threshold=low
 
       - name: Upload result to GitHub Code Scanning
         uses: github/codeql-action/upload-sarif@v2
         with:
           sarif_file: snyk.sarif
       
-      - name: result snyk scan
-        env:
-          snyk_scan_result_outcome: ${{ steps.snyk_scan.outcome }}
-          snyk_scan_result_conclusion: ${{ steps.snyk_scan.conclusion }}
-        run: echo "1 -> $snyk_scan_result_outcome \t 2 -> $snyk_scan_result_conclusion"       
+      - name: Snyk Scan Result Check
+        if: ${{ steps.snyk_scan.outcome == 'failure' }}
+        run: |
+          echo "::error file={name},line={line},endLine={endLine},title={title}::{message}"
+          exit 1     
 
+      - name: Build & tag, and push docker image to Amazon ECR
+        env:
+          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+          REPOSITORY: digiboard
+          IMAGE_TAG: latest
+        run: |
+          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
+
+      # - name: result snyk scan
+      #   env:
+      #     snyk_scan_result_outcome: ${{ steps.snyk_scan.outcome }}
+      #     snyk_scan_result_conclusion: ${{ steps.snyk_scan.conclusion }}
+      #   run: echo "1 -> $snyk_scan_result_outcome \t 2 -> $snyk_scan_result_conclusion"           
       # - name: Set up Docker Buildx
       #   id: buildx
       #   uses: docker/setup-buildx-action@master
